part 'quiz_quest.dart';

class Card3D {
  Card3D({this.image, this.name, this.text, this.questions});
  final String? image;
  final String? name;
  final String? text;
  final List? questions;
}

final cardList = [
  Card3D(
      image: 'assets/3D_card_animation/1.png',
      name: 'History of Soccer',
      text:
          'Soccer, also known as football in many parts of the world, has a rich and fascinating history that spans centuries. From its humble beginnings to becoming the world\'s most popular sport, let\'s take a closer look at the highlights of soccer\'s historical journey.\n\nI. Ancient Origins:\nThe earliest forms of soccer can be traced back to ancient civilizations such as the Chinese, Greeks, and Romans.\nChinese military during the Han Dynasty played a game called "Cuju" around the 2nd and 3rd centuries BC. It involved kicking a ball into a net.\nThe Greeks also had a game called "Episkyros", in which players would aim to get their ball past a zealous group of opponents.\nThe Romans later adopted this game and called it "Harpastum", played with a smaller ball and representing military tactics.\n\nII. Medieval Era:\nDuring the Middle Ages, soccer-like games were immensely popular in Europe, albeit with varying rules.\nA game called "Mob Football" was played in English towns and villages, where players would try to kick the ball from one landmark to another.\nThe rules of these early games were often unruly, with large groups of players and no formal boundaries.\n\nIII. Modernization and Standardization:\nIn the 19th century, soccer underwent formalization and standardized rules were established.\nThe Cambridge Rules, created in 1848 by the University of Cambridge, were influential in shaping soccer\'s regulations.\nIn 1863, the Football Association (FA) was founded in England, becoming the world\'s first governing body for soccer.\nThe combination of these efforts led to the birth of modern soccer, characterized by defined rules and clear structure.\n\nIV. Global Expansion:\nSoccer began to spread internationally in the late 19th and early 20th centuries.\nThe first international soccer match took place in 1872 between England and Scotland.\nThe FIFA (Fédération Internationale de Football Association) was founded in 1904, becoming the global governing body for soccer.\nThe FIFA World Cup, first held in 1930, has become the pinnacle of international soccer, bringing nations together in a celebration of sport.\n\nV. The Modern Game:\nToday, soccer has become the world\'s most popular sport, with billions of fans and players worldwide.\nThe sport has witnessed iconic moments, legendary players, and remarkable tournaments that have captivated fans across nerations.\nClub competitions like the English Premier League, La Liga, and the UEFA Champions League showcase the best talent and create fierce rivalries.\nSoccer continues to evolve, with technological advancements, video assistant referees (VAR), and increasing efforts to enhance fairness and integrity.',
      questions: soccerQuest),
  Card3D(
      image: 'assets/3D_card_animation/2.png',
      name: 'Lionel Messi',
      text:
          'Lionel Messi is an Argentine professional footballer widely regarded as one of the greatest players of all time. Born on June 24, 1987, in Rosario, Argentina, Messi\'s talent for the sport was evident at an early age. He joined FC Barcelona\'s youth academy, La Masia, at the age of 13, and quickly rose through the ranks to make his first-team debut at just 16 years old.\n\nMessi has enjoyed tremendous success throughout his career, both individually and with his club team. He has won numerous accolades, including seven Ballon d\'Or titles, awarded to the best player in the world. Messi has also helped Barcelona win numerous championships, including 10 La Liga titles and four UEFA Champions League titles. His ability to score goals, create scoring opportunities, and dribble past defenders has made him a formidable force on the field.\n\nIn addition to his success with Barcelona, Messi has also represented the Argentine national team at several international tournaments. While he has come close to winning major trophies with his country, including reaching the finals of the 2014 FIFA World Cup and the Copa America, he has yet to secure a major international title. Nonetheless, Messi\'s contribution to the Argentine national team cannot be understated, as he has consistently been the team\'s top scorer and playmaker.\n\nOff the field, Messi is known for his humility and philanthropy. He is involved in various charitable initiatives, including the Leo Messi Foundation, which supports access to education and healthcare for vulnerable children. Messi\'s contributions to the sport and society have earned him admiration and respect from fans around the world.',
      questions: lionelMessi),
  Card3D(
      image: 'assets/3D_card_animation/3.jpg',
      name: 'Cristiano Ronaldo',
      text:
          'Cristiano Ronaldo, born on February 5, 1985, is a Portuguese professional footballer who currently plays as a forward for Juventus and the Portugal national team. He is considered one of the greatest footballers of all time and has won numerous awards throughout his career.\n\nRonaldo began his professional career with Sporting CP in Portugal before moving to Manchester United in 2003. During his time at Manchester United, he won three Premier League titles, one Champions League title, and one Ballon d\'Or award.\n\nIn 2009, Ronaldo transferred to Real Madrid for a then-world record transfer fee of €94 million. He went on to win four Champions League titles, two La Liga titles, and four Ballon d\'Or awards during his time at Real Madrid. In 2018, he transferred to Juventus for a fee of €100 million.\n\nRonaldo has also had great success with the Portugal national team. He has scored over 100 goals for his country and helped lead them to victory in the 2016 European Championship.\n\nOff the field, Ronaldo is known for his philanthropic work and has donated millions of dollars to various charities. He is also a fashion icon and has launched his own clothing line.',
      questions: cristianoRonaldo),
  Card3D(
      image: 'assets/3D_card_animation/4.jpg',
      name: 'Xavi',
      text:
          'Xavi, born on January 25, 1980, is a retired Spanish professional footballer who is widely considered one of the greatest midfielders of all time. He spent the majority of his career with Barcelona, where he won numerous titles and accolades.\n\nXavi began his career with Barcelona\'s youth academy, La Masia, and made his debut for the first team in 1998. He quickly established himself as a key player for the club and went on to win eight La Liga titles, four Champions League titles, and two Club World Cup titles during his time with Barcelona.\n\nKnown for his exceptional passing ability and vision on the field, Xavi was a crucial player in Barcelona\'s tiki-taka style of play under manager Pep Guardiola. He also played a key role in Spain\'s national team, helping them win the 2010 World Cup and the 2008 and 2012 European Championships.\n\nAfter leaving Barcelona in 2015, Xavi played for Qatari club Al-Sadd before retiring in 2019. He has since begun his coaching career, currently serving as the head coach of Qatari club Al-Sadd.',
      questions: xavi),
  Card3D(
      image: 'assets/3D_card_animation/5.jpg',
      name: 'Andres Iniesta',
      text:
          'Andres Iniesta, born on May 11, 1984, is a retired Spanish professional footballer who is widely regarded as one of the greatest midfielders of his generation. He spent the majority of his career with Barcelona, where he won numerous titles and accolades.\n\nIniesta began his career with Barcelona\'s youth academy, La Masia, and made his debut for the first team in 2002. He quickly established himself as a key player for the club and went on to win nine La Liga titles, four Champions League titles, and three Club World Cup titles during his time with Barcelona.\n\nKnown for his exceptional dribbling skills and ability to control the tempo of a match, Iniesta was a crucial player in Barcelona\'s tiki-taka style of play under manager Pep Guardiola. He also played a key role in Spain\'s national team, helping them win the 2010 World Cup and the 2008 and 2012 European Championships.\n\nIniesta left Barcelona in 2018 to join Japanese club Vissel Kobe, where he played until his retirement in 2020. He is widely regarded as one of the greatest players in Barcelona\'s history and one of the best midfielders of all time.',
      questions: andresIniesta),
  Card3D(
      image: 'assets/3D_card_animation/6.jpg',
      name: 'Zlatan Ibrahimovic',
      text:
          'Zlatan Ibrahimovic, born on October 3, 1981, is a Swedish professional footballer who is widely regarded as one of the best strikers of his generation. He has played for numerous top clubs throughout his career, including Ajax, Juventus, Inter Milan, Barcelona, AC Milan, Paris Saint-Germain, Manchester United, and currently, AC Milan.\n\nIbrahimovic began his career with Swedish club Malmo FF before moving to Ajax in 2001. He quickly established himself as a prolific scorer and went on to win two Eredivisie titles with the club. He then moved to Juventus, where he won two Serie A titles but was later stripped of them due to the Calciopoli scandal.\n\nAfter a brief stint with Inter Milan, Ibrahimovic moved to Barcelona in 2009. However, he struggled to adapt to the team\'s style of play and had a difficult relationship with manager Pep Guardiola. He then moved to AC Milan on loan before signing permanently and helping the club win their first Serie A title in seven years.\n\nIbrahimovic has also had success with the Swedish national team, scoring 62 goals in 116 appearances and helping them reach the quarter-finals of the 2002 and 2006 World Cups.\n\nKnown for his physicality, technical ability, and powerful shot, Ibrahimovic has won numerous individual awards throughout his career and is widely regarded as one of the best players in the history of Swedish football.',
      questions: zlatanIbrahimovic),
  Card3D(
      image: 'assets/3D_card_animation/7.jpg',
      name: 'Radamel Falcao',
      text:
          'Radamel Falcao, born on February 10, 1986, is a Colombian professional footballer who is widely regarded as one of the best strikers of his generation. He has played for numerous top clubs throughout his career, including River Plate, FC Porto, Atletico Madrid, Monaco, and currently, Galatasaray.\n\nFalcao began his career with Colombian club Lanceros Boyaca before moving to River Plate in 2001. He quickly established himself as a prolific scorer and helped the club win the Argentine Primera Division title in 2008. He then moved to Porto, where he won three Primeira Liga titles and the UEFA Europa League.\n\nAfter a successful stint with Atletico Madrid, where he won the UEFA Europa League and reached the UEFA Champions League final, Falcao moved to Monaco in 2013. He helped the club win the Ligue 1 title in his first season but suffered a serious knee injury that kept him out of the 2014 World Cup.\n\nFalcao has also had success with the Colombian national team, scoring 34 goals in 96 appearances and helping them reach the quarter-finals of the 2014 World Cup.\n\nKnown for his clinical finishing, aerial ability, and positioning, Falcao has won numerous individual awards throughout his career and is widely regarded as one of the best players in the history of Colombian football.',
      questions: radamelFalcao),
  Card3D(
      image: 'assets/3D_card_animation/8.jpg',
      name: 'Robin van Persie',
      text:
          'Robin van Persie, born on August 6, 1983, is a retired Dutch professional footballer who played as a striker. He is widely regarded as one of the best players of his generation and has played for top clubs such as Feyenoord, Arsenal, Manchester United, and Fenerbahce.\n\nVan Persie began his career with Feyenoord in his native Netherlands before moving to Arsenal in 2004. He quickly established himself as a prolific scorer and helped the club win the FA Cup in 2005. He went on to win the Premier League Golden Boot in the 2011-2012 season after scoring 30 goals.\n\nIn 2012, van Persie made a controversial move to Arsenal\'s rival, Manchester United. He had an immediate impact, helping the club win the Premier League title in his first season and scoring 26 goals in the process. He also won the Premier League Golden Boot for the second time in his career.\n\nVan Persie retired from international football in 2018 after scoring 50 goals in 102 appearances for the Netherlands. He played in three World Cups and helped the team reach the final in 2010.\n\nKnown for his technical ability, vision, and finishing, van Persie has won numerous individual awards throughout his career and is widely regarded as one of the best strikers in the history of Dutch football.',
      questions: robinvanPersie),
  Card3D(
      image: 'assets/3D_card_animation/9.jpg',
      name: 'Andrea Pirlo',
      text:
          'Andrea Pirlo, born on May 19, 1979, is a retired Italian professional footballer who played as a midfielder. He is widely regarded as one of the best midfielders of his generation and has played for top clubs such as AC Milan, Juventus, and New York City FC.\n\nPirlo began his career with Brescia in Italy before moving to AC Milan in 2001. He quickly established himself as a key player and helped the club win two Serie A titles and the UEFA Champions League in 2003 and 2007. He also won the FIFA World Cup with Italy in 2006.\n\nIn 2011, Pirlo made a controversial move to Juventus, where he became a fan favorite and helped the club win four consecutive Serie A titles from 2012 to 2015. He also reached the UEFA Champions League final with Juventus in 2015.\n\nPirlo retired from professional football in 2018 after playing for New York City FC in Major League Soccer. He was known for his exceptional passing ability, vision, and free-kick taking skills. He won numerous individual awards throughout his career and is widely regarded as one of the best midfielders in the history of Italian football.',
      questions: andreaPirlo),
  Card3D(
      image: 'assets/3D_card_animation/10.jpg',
      name: 'Yaya Toure',
      text:
          'Yaya Toure is a retired Ivorian professional footballer who played as a midfielder. He was born on May 13, 1983, in Bouake, Ivory Coast. Toure began his career with ASEC Mimosas in Ivory Coast before moving to Europe to play for Beveren in Belgium and then Metalurh Donetsk in Ukraine.\n\nIn 2007, Toure signed with Barcelona, where he became a key player and helped the club win two La Liga titles and the UEFA Champions League in 2009. He also won the African Cup of Nations with Ivory Coast in 2015.\n\nIn 2010, Toure made a move to Manchester City, where he became a fan favorite and helped the club win three Premier League titles from 2012 to 2014. He also won the African Cup of Nations with Ivory Coast again in 2015.\n\nToure retired from professional football in 2019 after playing for various clubs including Olympiacos, Qingdao Huanghai, and Leyton Orient. He was known for his powerful runs, physicality, and goal-scoring ability from midfield. He won numerous individual awards throughout his career and is widely regarded as one of the best African players of all time.',
      questions: yayaToure),
];
